CREATE table MANDATE(
ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NAME VARCHAR(20) UNIQUE NOT NULL,
ACCEPTED_RISK_LEVEL VARCHAR(7) NOT NULL,
CREATION_DATETIME TIMESTAMP NOT NULL,
START_DATE DATE NOT NULL,
END_DATE DATE NOT NULL,
BOOK_ID BIGINT NOT NULL,
INITIAL_CASH_AMOUNT  DECIMAL(30,15) NOT NULL,
INITIAL_CASH_CURRENCY  VARCHAR(3) NOT NULL,
CONSTRAINT FK_MANDATE_BOOK_ID FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID));
