CREATE table NORMAL_PROBABILITY_DISTRIBUTION(
PROBABILITY_DISTRIBUTION_ID BIGINT,
MEAN SMALLINT NOT NULL,
VARIANCE SMALLINT NOT NULL,
CONSTRAINT FK_NORMAL_PROBABILITY_DISTRIBUTION_ID_ID FOREIGN KEY (NORMAL_PROBABILITY_DISTRIBUTION_ID) REFERENCES PROBABILITY_DISTRIBUTION(ID));