CREATE TABLE ACTION_GUARD 
(ACTION_ID BIGINT NOT NULL,
GUARDS_ID BIGINT NOT NULL UNIQUE, 
PRIMARY KEY (ACTION_ID, GUARDS_ID));
ALTER TABLE ACTION_GUARD ADD CONSTRAINT FKcv2x2dlpwf20axxx3hgpx9i8n FOREIGN KEY (GUARDS_ID) REFERENCES GUARD;
ALTER TABLE ACTION_GUARD ADD CONSTRAINT FKdx0fa1ci4xcfkxmsjnjn8f70j FOREIGN KEY (ACTION_ID) REFERENCES ACTION;