CREATE SEQUENCE ACTION_SEQ START WITH 1 INCREMENT BY 50;
CREATE TABLE ACTION 
(ARRIVAL_STATUS_ID BIGINT,
DEPARTURE_STATUS_ID BIGINT,
GUARD_ID BIGINT UNIQUE,
ID BIGINT NOT NULL,
WORKFLOW_ID BIGINT,
NAME VARCHAR(255),
PRIMARY KEY (ID));
ALTER TABLE Action ADD CONSTRAINT FK8oidguw8kw2dg7xy02konsxsf FOREIGN KEY (ARRIVAL_STATUS_ID) REFERENCES STATUS;
ALTER TABLE Action ADD CONSTRAINT FK4etbhf1ymguyap1702sr2cgkg FOREIGN KEY (GUARD_ID) REFERENCES GUARD;
ALTER TABLE Action ADD CONSTRAINT FK2ju7c0t7fbl3hmvo37ba9pulc FOREIGN KEY (WORKFLOW_ID) REFERENCES WORKFLOW;