CREATE SEQUENCE ACTION_SEQ START WITH 1 INCREMENT BY 50;
CREATE TABLE ACTION 
(DEPARTURE_STATUS_ID BIGINT,
ID BIGINT NOT NULL,
WORKFLOW_ID BIGINT,
NAME VARCHAR(255),
PRIMARY KEY (ID));
ALTER TABLE Action ADD CONSTRAINT FKa78f9sjwn2nc8gxythjw2l54w FOREIGN KEY (DEPARTURE_STATUS_ID) REFERENCES STATUS;
ALTER TABLE Action ADD CONSTRAINT FK2ju7c0t7fbl3hmvo37ba9pulc FOREIGN KEY (WORKFLOW_ID) REFERENCES WORKFLOW;