CREATE table ALLOCATION_CONFIGURATION_BOOK(
ALLOCATION_CONFIGURATION_ID BIGINT NOT NULL, 
BOOK_ID BIGINT NOT NULL,
CONSTRAINT FK_ALLOCATION_CONFIGURATION_BOOK_ALLOCATION_CONFIGURATION_ID FOREIGN KEY (ALLOCATION_CONFIGURATION_ID) REFERENCES ALLOCATION_CONFIGURATION(ID),
CONSTRAINT FK_ALLOCATION_CONFIGURATION_BOOK_BOOK_ID FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID));