CREATE table BOOK(
ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
NAME VARCHAR(20) NOT NULL,
PROCESSING_ORG_ID BIGINT,
DESCRIPTION VARCHAR(500),
CONSTRAINT FK_BOOK_PROCESSNG_ORG_ID FOREIGN KEY (PROCESSING_ORG_ID) REFERENCES LEGAL_ENTITY(ID),
CONSTRAINT UC_BOOK_NAME_PROCESSING_ORG_ID UNIQUE (NAME, PROCESSING_ORG_ID));