CREATE table CASH_INVENTORY(
ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (START WITH 1, INCREMENT BY 1),
CURRENCY_ID BIGINT NOT NULL,
BOOK_ID BIGINT NOT NULL,
FROM_DATE DATE NOT NULL,
TO_DATE DATE,
AMOUNT DECIMAL(30,15) NOT NULL,
CONSTRAINT FK_CASH_INVENTORY_CURRENCY_ID FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY(ID),
CONSTRAINT FK_CASH_INVENTORY_BOOK_ID FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID));