CREATE table CCYSWAP_TRADE(
CCYSWAP_TRADE_ID BIGINT PRIMARY KEY,
CURRENCY_TWO_ID BIGINT NOT NULL,
NOTIONAL_AMOUNT_TWO DECIMAL(30,15) NOT NULL,
CONSTRAINT FK_CCYSWAP_CURRENCY_TWO_ID FOREIGN KEY (CURRENCY_TWO_ID) REFERENCES CURRENCY(ID),
CONSTRAINT FK_CCYSWAP_TRADE_ID FOREIGN KEY (CCYSWAP_TRADE_ID) REFERENCES IRSWAP_TRADE(IRSWAP_TRADE_ID));
