CREATE TABLE CONDITIONALACTION 
(CHOICEPSEUDOSTATUS_ID BIGINT,
CONDITION_ID BIGINT,
ID BIGINT NOT NULL,
PRIMARY KEY (ID));
ALTER TABLE CONDITIONALACTION ADD CONSTRAINT FKr9dd4vbxugh2mcp0i3v2wxq86 FOREIGN KEY (CHOICEPSEUDOSTATUS_ID) REFERENCES STATUS;
ALTER TABLE CONDITIONALACTION ADD CONSTRAINT FKnvemyafdeej42kq6f8csr0beb FOREIGN KEY (CONDITION_ID) REFERENCES CONDITION;
ALTER TABLE CONDITIONALACTION ADD CONSTRAINT FK6ftq4ehv62pqtvu33tvq2w70r FOREIGN KEY (ID) REFERENCES ACTION;