CREATE TABLE CONDITIONALACTION_STATUS 
(CONDITIONALROUTING_KEY INTEGER NOT NULL,
CONDITIONALACTION_ID BIGINT NOT NULL,
CONDITIONALROUTING_ID BIGINT NOT NULL UNIQUE,
PRIMARY KEY (CONDITIONALROUTING_KEY, CONDITIONALACTION_ID));
ALTER TABLE CONDITIONALACTION_STATUS ADD CONSTRAINT FKs6rokfesp2efboi8p6gsc4o8d FOREIGN KEY (CONDITIONALROUTING_ID) REFERENCES STATUS;
ALTER TABLE CONDITIONALACTION_STATUS ADD CONSTRAINT FK5mw7ijvug5oxh44ys63jncqyb FOREIGN KEY (CONDITIONALACTION_ID) REFERENCES CONDITIONALACTION;