CREATE TABLE CONDITIONALACTION_PROCESS 
(CONDITIONALACTION_ID BIGINT NOT NULL,
CONDITIONALPROCESSES_KEY BIGINT NOT NULL,
CONDITIONALPROCESSES_ID BIGINT NOT NULL UNIQUE,
PRIMARY KEY (CONDITIONALACTION_ID, CONDITIONALPROCESSES_KEY));
ALTER TABLE CONDITIONALACTION_PROCESS ADD CONSTRAINT FK1q3hyhpeg1dyuj8ylfgycxbt9 FOREIGN KEY (CONDITIONALPROCESSES_ID) REFERENCES PROCESS;
ALTER TABLE CONDITIONALACTION_PROCESS ADD CONSTRAINT FKrspaghld0ecm5sad0cofdfcwr FOREIGN KEY (CONDITIONALPROCESSES_KEY) REFERENCES STATUS;
ALTER TABLE CONDITIONALACTION_PROCESS ADD CONSTRAINT FKnnbwk2411am0mu4f3e2dil3rs FOREIGN KEY (CONDITIONALACTION_ID) REFERENCES CONDITIONALACTION;