CREATE TABLE CONDITIONALACTION_SIMPLEACTION 
(CONDITIONALACTION_ID BIGINT NOT NULL,
CONDITIONALACTIONS_ID BIGINT NOT NULL UNIQUE,
PRIMARY KEY (CONDITIONALACTION_ID, CONDITIONALACTIONS_ID));
ALTER TABLE CONDITIONALACTION_SIMPLEACTION ADD CONSTRAINT FK5k83inaogyb7mcx8du4is3mw3 FOREIGN KEY (CONDITIONALACTIONS_ID) REFERENCES SIMPLEACTION;
ALTER TABLE CONDITIONALACTION_SIMPLEACTION ADD CONSTRAINT FKmevd4k8syqtsaq0um60l5w30n FOREIGN KEY (CONDITIONALACTION_ID) REFERENCES CONDITIONALACTION;