CREATE table CURRENCY(
ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (START WITH 1, INCREMENT BY 1), 
ISO_CODE VARCHAR(3) UNIQUE NOT NULL,
NAME VARCHAR(20) UNIQUE,
NON_DELIVERABLE BOOLEAN,
FIXING_DATE_OFFSET BIGINT,
CALENDAR_ID BIGINT,
CONSTRAINT FK_CURRENCY_CALENDAR_ID FOREIGN KEY (CALENDAR_ID) REFERENCES CALENDAR(ID));