CREATE table CURVE_QUOTE(
CURVE_ID BIGINT, 
QUOTE_ID BIGINT,
CONSTRAINT FK_CQ_CURVE_ID FOREIGN KEY (CURVE_ID) REFERENCES CURVE(ID),
CONSTRAINT FK_CQ_QUOTE_ID FOREIGN KEY (QUOTE_ID) REFERENCES QUOTE(ID)
);