CREATE table CURVE(
ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (START WITH 1, INCREMENT BY 1), 
NAME VARCHAR(50) NOT NULL,
ALGORITHM VARCHAR(40),
INTERPOLATOR VARCHAR(50),
INSTANCE VARCHAR(20),
QUOTE_DATE DATE,
QUOTE_SET_ID BIGINT,
PROCESSING_ORG_ID BIGINT,
CONSTRAINT FK_CU_QUOTE_SET_ID FOREIGN KEY (QUOTE_SET_ID) REFERENCES QUOTE_SET(ID),
CONSTRAINT FK_CU_PROCESSING_ORG_ID FOREIGN KEY (PROCESSING_ORG_ID) REFERENCES LEGAL_ENTITY(ID));