CREATE table DAILY_PNL(
ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (START WITH 1, INCREMENT BY 1),
POSITION_DEFINITION_ID BIGINT,
CALENDAR_ID BIGINT,
PNL DECIMAL(30,15),
REALIZED_PNL DECIMAL(30,15),
UNREALIZED_PNL DECIMAL(30,15),
VALUE_DATE DATE,
CONSTRAINT FK_DAILY_PNL_POSITION_DEFINITION_ID FOREIGN KEY (POSITION_DEFINITION_ID) REFERENCES POSITION_DEFINITION(ID),
CONSTRAINT FK_DAILY_PNL_CALENDAR_ID FOREIGN KEY (CALENDAR_ID) REFERENCES CALENDAR(ID));