CREATE table DATE_RULE(
ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (START WITH 1, INCREMENT BY 1), 
NAME VARCHAR(50) UNIQUE NOT NULL,
IS_SEQUENCE BOOLEAN NOT NULL,
POSITION VARCHAR(4),
DATE_OFFSET SMALLINT,
DATE_ROLLING_CONVENTION VARCHAR(20),
WEEK_DAY VARCHAR(9)
);
