CREATE table EQUITY_OPTION_VOLATILITY_SURFACE_POINT(
VOLATILITY_SURFACE_ID BIGINT, 
OPTION_EXPIRY INTEGER, 
STRIKE DECIMAL(30,15),
VOLATILITY DECIMAL(30,15) ,
CONSTRAINT FK_EQUITY_OPTION_VOLATILITY_SURFACE_ID FOREIGN KEY (VOLATILITY_SURFACE_ID) REFERENCES VOLATILITY_SURFACE(ID));