CREATE table EQUITY(
PRODUCT_ID BIGINT PRIMARY KEY, 
TRADING_SIZE BIGINT, 
TOTAL_ISSUED BIGINT, 
PAY_DIVIDEND BOOLEAN,
DIVIDEND_CURRENCY_ID BIGINT,
DIVIDEND_FREQUENCY VARCHAR(20),
ACTIVE_FROM DATE,
ACTIVE_TO DATE,
CONSTRAINT FK_EQUITY_SECURITY_ID FOREIGN KEY (PRODUCT_ID) REFERENCES SECURITY(PRODUCT_ID),
CONSTRAINT FK_EQUITY_CURRENCY_ID FOREIGN KEY (DIVIDEND_CURRENCY_ID) REFERENCES CURRENCY(ID));