CREATE table EQUITY_OPTION(
PRODUCT_ID BIGINT, 
CODE VARCHAR(20) NOT NULL, 
TYPE VARCHAR(4) NOT NULL, 
EQUITY_ID  BIGINT,
STRIKE DECIMAL(30,15) NOT NULL,
MATURITY_DATE DATE NOT NULL,
EQUITY_OPTION_CONTRACT_SPECIFICATION_ID BIGINT,
CONSTRAINT FK_EQUITY_OPTION_CONTRACT_SPECIFICATION_ID FOREIGN KEY (EQUITY_OPTION_CONTRACT_SPECIFICATION_ID) REFERENCES EQUITY_OPTION_CONTRACT_SPECIFICATION(ID),
CONSTRAINT FK_EQUITY_OPTION_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID),
CONSTRAINT FK_EQUITY_OPTION_UNDERLYING_ID FOREIGN KEY (EQUITY_ID) REFERENCES EQUITY(PRODUCT_ID));