CREATE table EQUITY_OPTION_CONTRACT_SPECIFICATION(
ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (START WITH 1, INCREMENT BY 1), 
NAME VARCHAR(20) NOT NULL,  
EXCHANGE_ID  BIGINT,
MATURITY_DATES_DATE_RULE_ID BIGINT,
QUANTITY DECIMAL(30,15) NOT NULL,
STYLE VARCHAR(50) NOT NULL,
SETTLEMENT_TYPE VARCHAR(50) NOT NULL,
SETTLEMENT_DATE_OFFSET SMALLINT NOT NULL,
MULTIPLIER DECIMAL(30,15) NOT NULL,
PREMIUM_CURRENCY_ID  BIGINT,
CONSTRAINT FK_EQUITY_OPTION_SPECIFICATION_EXCHANGE_ID FOREIGN KEY (EXCHANGE_ID) REFERENCES EXCHANGE(ID),
CONSTRAINT FK_EQUITY_OPTION_SPECIFICATION_MATURITY_DATES_ID FOREIGN KEY (MATURITY_DATES_DATE_RULE_ID) REFERENCES DATE_RULE(ID),
CONSTRAINT FK_EQUITY_OPTION_SPECIFICATION_PREMIUM_CURRENCY_ID FOREIGN KEY (PREMIUM_CURRENCY_ID) REFERENCES CURRENCY(ID));