CREATE table ERROR(
ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (START WITH 1, INCREMENT BY 1), 
TYPE VARCHAR(50) NOT NULL,
STATUS VARCHAR(10) NOT NULL,
MESSAGE VARCHAR(1000) NOT NULL,
ERROR_DATE TIMESTAMP NOT NULL,
SOLVING_DATE TIMESTAMP);