CREATE table EXCHANGE(
ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (START WITH 1, INCREMENT BY 1), 
CODE VARCHAR(10) UNIQUE NOT NULL,
NAME VARCHAR(50) UNIQUE,
IS_OTC BOOLEAN,
CALENDAR_ID BIGINT,
CONSTRAINT FK_EXCHANGE_CALENDAR_ID FOREIGN KEY (CALENDAR_ID) REFERENCES CALENDAR(ID));