CREATE table FRA_TRADE(
FRA_TRADE_ID BIGINT PRIMARY KEY,
START_DATE DATE NOT NULL,
FIXED_RATE DECIMAL(30,15) NOT NULL,
CONSTRAINT FK_FRA_TRADE_ID FOREIGN KEY (FRA_TRADE_ID) REFERENCES IRFORWARD_TRADE(IRFORWARD_TRADE_ID)
);