CREATE table FUTURE_TRADE(
FUTURE_TRADE_ID BIGINT PRIMARY KEY, 
QUANTITY DECIMAL NOT NULL,
CONSTRAINT FK_FUTURE_TRADE_ID FOREIGN KEY (FUTURE_TRADE_ID) REFERENCES IRFORWARD_TRADE(IRFORWARD_TRADE_ID)
);