CREATE table FUTURE(
FUTURE_ID BIGINT PRIMARY KEY,
FUTURE_CONTRACT_SPECIFICATION_ID BIGINT,
SYMBOL VARCHAR(50) NOT NULL,
MATURITY_DATE DATE NOT NULL,
CONSTRAINT FK_FUTURE_PRODUCT_ID FOREIGN KEY (FUTURE_ID) REFERENCES PRODUCT(ID),
CONSTRAINT FK_FUTURE_CONTRACT_SPECIFICATION_ID FOREIGN KEY (FUTURE_CONTRACT_SPECIFICATION_ID) REFERENCES FUTURE_CONTRACT_SPECIFICATION(ID));
