CREATE table FX_VOLATILITY_SURFACE_DELTA(
DELTA_ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (START WITH 1, INCREMENT BY 1),
SURFACE_ID BIGINT, 
VALUE DECIMAL(30,15),
CONSTRAINT FK_VSD_CURVE_ID FOREIGN KEY (SURFACE_ID) REFERENCES VOLATILITY_SURFACE(ID));