CREATE table FXSPOT_TRADE(
FXSPOT_TRADE_ID BIGINT,
CURRENCY_ONE_ID BIGINT,
AMOUNT_ONE DECIMAL(30,15),
CONSTRAINT FK_FXSPOT_TRADE_ID FOREIGN KEY (FXSPOT_TRADE_ID) REFERENCES TRADE(ID),
CONSTRAINT FK_CURRENCY_ONE_ID FOREIGN KEY (CURRENCY_ONE_ID) REFERENCES CURRENCY(ID));
