CREATE table FXSWAP_TRADE(
FXSWAP_TRADE_ID BIGINT,
CURRENCY_ONE_ID BIGINT,
SETTLEMENT_DATE_FORWARD DATE,
AMOUNT_ONE_FORWARD DECIMAL(30,15),
AMOUNT_ONE_SPOT DECIMAL(30,15),
AMOUNT_TWO_FORWARD DECIMAL(30,15),
CONSTRAINT FK_FXSWAP_TRADE_ID FOREIGN KEY (FXSWAP_TRADE_ID) REFERENCES TRADE(ID),
CONSTRAINT FK_FXSWAP_CURRENCY_ONE_ID FOREIGN KEY (CURRENCY_ONE_ID) REFERENCES CURRENCY(ID));
