CREATE table GCREPO_TRADE(
GCREPO_TRADE_ID BIGINT PRIMARY KEY, 
GCBASKET_ID BIGINT,
CONSTRAINT FK_GCREPO_TRADE_GCBASKET_ID FOREIGN KEY (GCBASKET_ID) REFERENCES GCBASKET(ID),
CONSTRAINT FK_GCREPO_TRADE_ID FOREIGN KEY (GCREPO_TRADE_ID) REFERENCES REPO_TRADE(REPO_TRADE_ID));