CREATE table HOLIDAY(
ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (START WITH 1, INCREMENT BY 1), 
DATE DATE NOT NULL,
CALENDAR_ID BIGINT,
CONSTRAINT FK_HOLIDAY_CALENDAR_ID FOREIGN KEY (CALENDAR_ID) REFERENCES CALENDAR(ID));