CREATE table IRCAP_FLOOR_COLLAR_TRADE(
IRCAP_FLOOR_COLLAR_TRADE_ID BIGINT PRIMARY KEY, 
CAP_STRIKE DECIMAL(30,15),
FLOOR_STRIKE DECIMAL(30,15),
IRFORWARD_TRADE_ID BIGINT,
CONSTRAINT FK_IRCAP_FLOOR_COLLAR_ID FOREIGN KEY (IRCAP_FLOOR_COLLAR_TRADE_ID) REFERENCES TRADE(ID),
CONSTRAINT FK_IRCAP_FLOOR_COLLAR_IRFORWARD_TRADE_ID FOREIGN KEY (IRFORWARD_TRADE_ID) REFERENCES IRFORWARD_TRADE(IRFORWARD_TRADE_ID)
);