CREATE TABLE JOB_EXECUTION (
   ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (START WITH 1, INCREMENT BY 1),
   TRIGGER_FIRE_INSTANCE_ID VARCHAR(200) NOT NULL,
   STATUS VARCHAR(50) NOT NULL,
   START_TIME TIMESTAMP NOT NULL,
   END_TIME TIMESTAMP,
   ERROR_CAUSE VARCHAR(500),
   JOB_INSTANCE_NAME VARCHAR(200) NOT NULL,
   PROCESSING_ORG VARCHAR(20),
   JOB_TYPE VARCHAR(50) NOT NULL
 )