CREATE table MONTH(
ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (START WITH 1, INCREMENT BY 1), 
MONTH VARCHAR(9) NOT NULL,
DATE_RULE_ID BIGINT,
CONSTRAINT FK_MONTH_DATE_RULE_ID FOREIGN KEY (DATE_RULE_ID) REFERENCES DATE_RULE(ID));