CREATE table PARTIAL_TERMINATION(
TRADE_ID BIGINT NOT NULL, 
DATE DATE NOT NULL,
REDUCTION DECIMAL(30,15) NOT NULL,
CONSTRAINT FK_PARTIAL_TERMINATION_TRADE_ID FOREIGN KEY (TRADE_ID) REFERENCES TRADE(ID));