CREATE table POSITION_CALCULATION_ERROR(
ERROR_ID BIGINT, 
VALUE_DATE DATE NOT NULL,
POSITION_DEFINITION_ID BIGINT,
TRADE_ID BIGINT,
PRODUCT_ID BIGINT,
CONSTRAINT FK_POSITION_CALCULATION_ERROR_POSITION_DEFINITION_ID FOREIGN KEY (POSITION_DEFINITION_ID) REFERENCES POSITION_DEFINITION(ID),
CONSTRAINT FK_POSITION_CALCULATION_ERROR_TRADE_ID FOREIGN KEY (TRADE_ID) REFERENCES TRADE(ID),
CONSTRAINT FK_POSITION_CALCULATION_ERROR_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID),
CONSTRAINT FK_POSITION_CALCULATION_ERROR_ERROR_ID FOREIGN KEY (ERROR_ID) REFERENCES ERROR(ID)
);