CREATE table POSITION(
ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (START WITH 1, INCREMENT BY 1),
POSITION_DEFINITION_ID BIGINT,
PNL DECIMAL(30,15),
REALIZED_PNL DECIMAL(30,15),
UNREALIZED_PNL DECIMAL(30,15),
QUANTITY DECIMAL(30,15),
AVERAGE_PRICE DECIMAL(30,15),
VALUE_DATETIME  TIMESTAMP,
CONSTRAINT FK_POSITION_POSITION_DEFINITION_ID FOREIGN KEY (POSITION_DEFINITION_ID) REFERENCES POSITION_DEFINITION(ID));