CREATE table PRICING_PARAMETER_FX_CURVE(
PRICING_PARAMETER_ID BIGINT NOT NULL, 
PRIMARY_CURRENCY_ID BIGINT NOT NULL,
QUOTE_CURRENCY_ID BIGINT NOT NULL,
FX_CURVE_ID BIGINT NOT NULL,
CONSTRAINT FK_PP_FX_CURVE_PRICING_PARAMETER_ID FOREIGN KEY (PRICING_PARAMETER_ID) REFERENCES PRICING_PARAMETER(ID),
CONSTRAINT FK_PP_FX_CURVE_PRIMARY_CURRENCY_ID FOREIGN KEY (PRIMARY_CURRENCY_ID) REFERENCES CURRENCY(ID),
CONSTRAINT FK_PP_FX_CURVE_QUOTE_CURRENCY_ID FOREIGN KEY (QUOTE_CURRENCY_ID) REFERENCES CURRENCY(ID),
CONSTRAINT FK_PP_FX_CURVE_FX_CURVE_ID FOREIGN KEY (FX_CURVE_ID) REFERENCES FX_CURVE(ID));