CREATE table PRICING_PARAMETER_SWAPTION_VOLATILITY_SURFACE(
PRICING_PARAMETER_ID BIGINT NOT NULL, 
INDEX_ID BIGINT NOT NULL,
VOLATILITY_SURFACE_ID BIGINT NOT NULL,
CONSTRAINT FK_PP_SWAPTION_VOLATILITY_SURFACE_PRICING_PARAMETER_ID FOREIGN KEY (PRICING_PARAMETER_ID) REFERENCES PRICING_PARAMETER(ID),
CONSTRAINT FK_PP_SWAPTION_VOLATILITY_SURFACE_INDEX_ID FOREIGN KEY (INDEX_ID) REFERENCES INDEX(ID),
CONSTRAINT FK_PP_SWAPTION_VOLATILITY_SURFACE_VOLATILITY_SURFACE_ID FOREIGN KEY (VOLATILITY_SURFACE_ID) REFERENCES VOLATILITY_SURFACE(ID));