CREATE table PRICING_PARAMETER_CUSTOM_PRICER(
PRICING_PARAMETER_ID BIGINT NOT NULL, 
PRODUCT_TYPE VARCHAR(20) NOT NULL,
PRICER_NAME VARCHAR(50) NOT NULL,
CONSTRAINT FK_PP_CUSTOM_PRICER_PRICING_PARAMETER_ID FOREIGN KEY (PRICING_PARAMETER_ID) REFERENCES PRICING_PARAMETER(ID));