CREATE table PRICING_PARAMETER_DIVIDEND_YIELD_CURVE(
PRICING_PARAMETER_ID BIGINT NOT NULL, 
EQUITY_ID BIGINT NOT NULL,
INTEREST_RATE_CURVE_ID BIGINT NOT NULL,
CONSTRAINT FK_PP_DIVIDEND_YIELD_CURVE_PRICING_PARAMETER_ID FOREIGN KEY (PRICING_PARAMETER_ID) REFERENCES PRICING_PARAMETER(ID),
CONSTRAINT FK_PP_DIVIDEND_YIELD_CURVE_EQUITY_ID FOREIGN KEY (EQUITY_ID) REFERENCES EQUITY(PRODUCT_ID),
CONSTRAINT FK_PP_DIVIDEND_YIELD_CURVE_INTEREST_RATE_CURVE_ID FOREIGN KEY (INTEREST_RATE_CURVE_ID) REFERENCES INTEREST_RATE_CURVE(ID));