CREATE table PRICING_PARAMETER_FX_VOLATILITY_SURFACE(
PRICING_PARAMETER_ID BIGINT NOT NULL, 
PRIMARY_CURRENCY_ID BIGINT NOT NULL,
QUOTE_CURRENCY_ID BIGINT NOT NULL,
VOLATILITY_SURFACE_ID BIGINT NOT NULL,
CONSTRAINT FK_PP_FX_VOLATILITY_SURFACE_PRICING_PARAMETER_ID FOREIGN KEY (PRICING_PARAMETER_ID) REFERENCES PRICING_PARAMETER(ID),
CONSTRAINT FK_PP_FX_VOLATILITY_SURFACE_PRIMARY_CURRENCY_ID FOREIGN KEY (PRIMARY_CURRENCY_ID) REFERENCES CURRENCY(ID),
CONSTRAINT FK_PP_FX_VOLATILITY_SURFACE_QUOTE_CURRENCY_ID FOREIGN KEY (QUOTE_CURRENCY_ID) REFERENCES CURRENCY(ID),
CONSTRAINT FK_PP_FX_VOLATILITY_SURFACE_VOLATILITY_SURFACE_ID FOREIGN KEY (VOLATILITY_SURFACE_ID) REFERENCES VOLATILITY_SURFACE(ID));