CREATE table PRICING_PARAMETER(
ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (START WITH 1, INCREMENT BY 1), 
NAME VARCHAR(20) NOT NULL,
QUOTE_SET_ID BIGINT NOT NULL,
PROCESSING_ORG_ID BIGINT,
CONSTRAINT FK_PRICING_PARAMETER_QUOTE_SET_ID FOREIGN KEY (QUOTE_SET_ID) REFERENCES QUOTE_SET(ID),
CONSTRAINT FK_PRICING_PARAMETER_PROCESSING_ORG_ID FOREIGN KEY (PROCESSING_ORG_ID) REFERENCES LEGAL_ENTITY(ID),
CONSTRAINT UC_PRICING_PARAMETER_NAME_PROCESSING_ORG_ID UNIQUE (NAME, PROCESSING_ORG_ID));