CREATE table PRICING_PARAMETER_VALUE(
PRICING_PARAMETER_ID BIGINT, 
NAME VARCHAR(50),
VALUE VARCHAR(50) ,
CONSTRAINT FK_PRICING_PARAMETER_ID FOREIGN KEY (PRICING_PARAMETER_ID) REFERENCES PRICING_PARAMETER(ID));