CREATE table PRICING_PARAMETER_UNREALIZED_PNL_CALCULATION(
PRICING_PARAMETER_ID BIGINT NOT NULL, 
BOOK_ID BIGINT,
PRODUCT_TYPE VARCHAR(20),
PNL_CALCULATION VARCHAR(14) NOT NULL,
CONSTRAINT FK_PP_UNREALIZED_PNL_CALCULATION_PRICING_PARAMETER_ID FOREIGN KEY (PRICING_PARAMETER_ID) REFERENCES PRICING_PARAMETER(ID),
CONSTRAINT FK_PP_UNREALIZED_PNL_CALCULATION_BOOK_ID FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID));