CREATE table PRODUCT(
ID          BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (START WITH 1, INCREMENT BY 1),
CREATION_DATE  DATE,
EXCHANGE_ID BIGINT,
CONSTRAINT FK_EXCHANGE_ID FOREIGN KEY (EXCHANGE_ID) REFERENCES EXCHANGE(ID));