CREATE table QUOTE_SET(
ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (START WITH 1, INCREMENT BY 1), 
NAME VARCHAR(50) NOT NULL,
PROCESSING_ORG_ID BIGINT,
CONSTRAINT FK_QUOTE_SET_PROCESSING_ORG_ID FOREIGN KEY (PROCESSING_ORG_ID) REFERENCES LEGAL_ENTITY(ID),
CONSTRAINT UC_QUOTE_SET_NAME_PROCESSING_ORG_ID UNIQUE (NAME, PROCESSING_ORG_ID));