CREATE table QUOTE(
ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (START WITH 1, INCREMENT BY 1), 
NAME VARCHAR(50) NOT NULL,
TYPE VARCHAR(20) NOT NULL,
CONSTRAINT UNIQUE_QUOTE UNIQUE (NAME, TYPE));