CREATE table SECURITY(
PRODUCT_ID BIGINT PRIMARY KEY, 
ISSUER_ID BIGINT,
ISIN VARCHAR(50) NOT NULL,
CURRENCY_ID BIGINT,
ISSUE_DATE DATE,
ISSUE_PRICE DECIMAL(30,15),
CONSTRAINT FK_SECURITY_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID),
CONSTRAINT FK_SECURITY_ISSUER_ID FOREIGN KEY (ISSUER_ID) REFERENCES LEGAL_ENTITY(ID),
CONSTRAINT FK_SECURITY_CURRENCY_ID FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY(ID));