CREATE TABLE SIMPLEACTION_PROCESS 
(SIMPLEACTION_ID BIGINT NOT NULL,
PROCESSES_ID BIGINT NOT NULL UNIQUE,
PRIMARY KEY (SIMPLEACTION_ID, PROCESSES_ID));
ALTER TABLE SIMPLEACTION_PROCESS ADD CONSTRAINT FKmgtbcjdbcpy0tystvh8mdfpr9 FOREIGN KEY (PROCESSES_ID) REFERENCES PROCESS;
ALTER TABLE SIMPLEACTION_PROCESS ADD CONSTRAINT FK21q3twl8anlg045q2e4uo4t4e FOREIGN KEY (SIMPLEACTION_ID) REFERENCES SIMPLEACTION;