CREATE table SPECIFICREPO_TRADE(
SPECIFICREPO_TRADE_ID BIGINT PRIMARY KEY, 
SECURITY_ID BIGINT,
CONSTRAINT FK_SPECIFICREPO_TRADE_SECURITY_ID FOREIGN KEY (SECURITY_ID) REFERENCES SECURITY(PRODUCT_ID),
CONSTRAINT FK_SPECIFICREPO_TRADE_ID FOREIGN KEY (SPECIFICREPO_TRADE_ID) REFERENCES REPO_TRADE(REPO_TRADE_ID));