CREATE SEQUENCE STATUS_SEQ START WITH 1 INCREMENT BY 50;
CREATE TABLE STATUS 
(ID BIGINT NOT NULL,
WORKFLOW_ID BIGINT,
NAME VARCHAR(255),
PRIMARY KEY (ID));
ALTER TABLE Status ADD CONSTRAINT FKorc5sw45pdkbx7vu80f5up4j FOREIGN KEY (WORKFLOW_ID) REFERENCES WORKFLOW;