CREATE table SWAPTION_VOLATILITY_SURFACE_POINT(
VOLATILITY_SURFACE_ID BIGINT, 
SWAPTION_LIFETIME INTEGER, 
SWAP_LIFETIME INTEGER, 
VOLATILITY DECIMAL(30,15) ,
CONSTRAINT FK_VOLATILITY_SURFACE_ID FOREIGN KEY (VOLATILITY_SURFACE_ID) REFERENCES VOLATILITY_SURFACE(ID));