CREATE table UI_CONFIGURATION(
ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (START WITH 1, INCREMENT BY 1), 
DECIMAL_SEPARATOR CHAR(1),
GROUPING_SEPARATOR CHAR(1),
ROUNDING_MODE VARCHAR(11),
DECIMAL_DIGITS SMALLINT,
STYLE VARCHAR(20),
USER_ID BIGINT,
CONSTRAINT FK_UI_CONFIGURATION_USER_ID FOREIGN KEY (USER_ID) REFERENCES TRADISTA_USER(ID)
);