CREATE TABLE TRADISTA_USER(
ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
FIRST_NAME VARCHAR(20) NOT NULL,
SURNAME VARCHAR(20) NOT NULL,
PROCESSING_ORG_ID BIGINT,
LOGIN VARCHAR(20) UNIQUE NOT NULL,
PASSWORD VARCHAR(20) NOT NULL,
CONSTRAINT FK_USER_LEGAL_ENTITY_ID FOREIGN KEY (PROCESSING_ORG_ID) REFERENCES LEGAL_ENTITY(ID));