CREATE table VANILLA_OPTION_TRADE(
VANILLA_OPTION_TRADE_ID BIGINT PRIMARY KEY, 
STYLE VARCHAR(50) NOT NULL,
TYPE VARCHAR(4) NOT NULL,
STRIKE DECIMAL(30,15) NOT NULL,
MATURITY_DATE DATE NOT NULL,
EXERCISE_DATE DATE,
UNDERLYING_TRADE_ID BIGINT,
SETTLEMENT_TYPE VARCHAR(50),
SETTLEMENT_DATE_OFFSET INTEGER,
QUANTITY DECIMAL(30,15),
CONSTRAINT FK_UNDERLYING_TRADE_ID FOREIGN KEY (UNDERLYING_TRADE_ID) REFERENCES TRADE(ID),
CONSTRAINT FK_VANILLA_OPTION_TRADE_ID FOREIGN KEY (VANILLA_OPTION_TRADE_ID) REFERENCES TRADE(ID)
);