CREATE table VOLATILITY_SURFACE_QUOTE(
SURFACE_ID BIGINT, 
QUOTE_ID BIGINT,
CONSTRAINT FK_VSQ_CURVE_ID FOREIGN KEY (SURFACE_ID) REFERENCES VOLATILITY_SURFACE(ID),
CONSTRAINT FK_VSQ_QUOTE_ID FOREIGN KEY (QUOTE_ID) REFERENCES QUOTE(ID)
);