CREATE table WEEK_END(
ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (START WITH 1, INCREMENT BY 1), 
DAY VARCHAR(9) NOT NULL,
CALENDAR_ID BIGINT,
CONSTRAINT FK_WEEK_END_CALENDAR_ID FOREIGN KEY (CALENDAR_ID) REFERENCES CALENDAR(ID));