CREATE table IF_EXPRESSION(
ID BIGINT PRIMARY KEY,
COMPLEX_PROBABILITY_DISTRIBUTION_ID BIGINT,
POSITION SMALLINT NOT NULL,
PREDICATE_ID BIGINT,
IF_CLAUSE_ID BIGINT,
ELSE_CLAUSE_ID BIGINT,
CONSTRAINT FK_IF_EXPRESSION_PREDICATE_ID FOREIGN KEY (PREDICATE_ID) REFERENCES PREDICATE(ID),
CONSTRAINT FK_IF_EXPRESSION_COMPLEX_PROBABILITY_DISTRIBUTION_ID FOREIGN KEY (COMPLEX_PROBABILITY_DISTRIBUTION_ID) REFERENCES COMPLEX_PROBABILITY_DISTRIBUTION(COMPLEX_PROBABILITY_DISTRIBUTION_ID),
CONSTRAINT FK_IF_EXPRESSION_IF_CLAUSE_ID FOREIGN KEY (IF_CLAUSE_ID) REFERENCES PROBABILITY_DISTRIBUTION(ID),
CONSTRAINT FK_IF_EXPRESSION_ELSE_CLAUSE_ID FOREIGN KEY (ELSE_CLAUSE_ID) REFERENCES PROBABILITY_DISTRIBUTION(ID)
);
