CREATE table MANDATE_PRODUCT_TYPE_ALLOCATION(
MANDATE_ID BIGINT,
PRODUCT_TYPE VARCHAR(20) NOT NULL,
MIN_ALLOCATION SMALLINT,
MAX_ALLOCATION SMALLINT,
CONSTRAINT FK_MANDATE_PRODUCT_TYPE_ALLOCATION_MANDATE_ID FOREIGN KEY (MANDATE_ID) REFERENCES MANDATE(ID));
