CREATE table MANDATE_CURRENCY_ALLOCATION(
MANDATE_ID BIGINT,
CURRENCY_ID BIGINT,
MIN_ALLOCATION SMALLINT,
MAX_ALLOCATION SMALLINT,
CONSTRAINT FK_MANDATE_CURRENCY_ALLOCATION_MANDATE_ID FOREIGN KEY (MANDATE_ID) REFERENCES MANDATE(ID),
CONSTRAINT FK_MANDATE_CURRENCY_ALLOCATION_CURRENCY_ID FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY(ID));
