CREATE table PREDICATE(
ID BIGINT PRIMARY KEY,
FUNCTION_CALL_ID BIGINT,
OPERATOR VARCHAR2(17),
VALUE_ID BIGINT,
RESULT BOOLEAN,
CONSTRAINT FK_PREDICATE_FUNCTION_CALL_ID FOREIGN KEY (FUNCTION_CALL_ID) REFERENCES FUNCTION_CALL(ID),
CONSTRAINT FK_PREDICATE_VALUE_ID FOREIGN KEY (VALUE_ID) REFERENCES VALUE_ID(ID));
